name: Pyinstaller

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade -r requirements.txt 
        pip install pyinstaller
    - name: Create binary
      run: |
        pyinstaller --onefile XiaomiUpdateInfo.py
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: XiaomiUpdateInfo-Linux
        path: '~/work/Xiaomi-Update-Info/Xiaomi-Update-Info/dist/XiaomiUpdateInfo'

    - if: ${{ matrix.os == 'windows-latest' }}
      name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: XiaomiUpdateInfo-Windows
        path: 'D:\a\Xiaomi-Update-Info\Xiaomi-Update-Info\dist\XiaomiUpdateInfo.exe'

    - if: ${{ matrix.os == 'macos-latest' }}
      name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: XiaomiUpdateInfo-Darwin
        path: '~/work/Xiaomi-Update-Info/Xiaomi-Update-Info/dist/XiaomiUpdateInfo'